target: models.second_stage.fm_model.ModelInference
params:
  enc_scale: 4
  enc_scale_dino: 4
  tokenizer_config:
    target: models.first_stage.vqgan.VQModelInference
    params:
      e_dim: 16
      encoder_config:
        target: networks.tokenizer.pretrained_models.Encoder
        params:
          resolution:
            - 288
            - 512
          patch_size: 16
          z_channels: 768
          pretrained_encoder: MAE
          normalize_embedding: true
  generator_config:
    target: networks.DiT.dit.SwinSTDiTNoExtraMLP
    params:
      modulate_time_attn: true
      window_size: [6, 4]
      causal_time_attn: true
      max_num_frames: 6
      hidden_size: 768
      depth: 24
      num_heads: 16
      mlp_ratio: 4
      input_size:
        - 18
        - 32
      patch_size: 1
      in_channels: 32
      dropout: 0.0
      ctx_noise_aug_ratio: 0.1
      ctx_noise_aug_prob: 0.5
      drop_ctx_rate: 0.5
